# Generated by Django 5.1.3 on 2026-01-02 21:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monthly_contracts', '0001_initial'),
        ('tenants', '0001_initial'),
        ('third_parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=50, verbose_name='Tipo')),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('dinero_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Dinero inicial')),
                ('dinero_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dinero final')),
                ('cuadre_realizado', models.BooleanField(default=False, verbose_name='Cuadre realizado')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Parqueadero')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Egreso')], max_length=10, verbose_name='Tipo de movimiento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='parking.caja', verbose_name='Caja')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Parqueadero')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('first_hour_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Tarifa primera hora')),
                ('additional_hour_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Tarifa hora adicional')),
                ('is_monthly', models.BooleanField(default=False, verbose_name='Es mensualidad')),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarifa mensual')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Parqueadero')),
            ],
            options={
                'verbose_name': 'Categoría de Vehículo',
                'verbose_name_plural': 'Categorías de Vehículos',
            },
        ),
        migrations.CreateModel(
            name='ParkingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('ticket_number', models.CharField(blank=True, max_length=20, verbose_name='Número de ticket')),
                ('placa', models.CharField(max_length=20, verbose_name='Placa')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('cascos', models.IntegerField(blank=True, null=True, verbose_name='Cascos')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora entrada')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora salida')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto pagado')),
                ('barcode', models.ImageField(blank=True, upload_to='barcodes/')),
                ('monthly_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_monthly_entry', models.BooleanField(default=False, verbose_name='Entrada con mensualidad')),
                ('monthly_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monthly_contracts.monthlycontract', verbose_name='Contrato mensual')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Parqueadero')),
                ('third_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='third_parties.thirdparty', verbose_name='Tercero')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehiclecategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Ticket de Estacionamiento',
                'verbose_name_plural': 'Tickets de Estacionamiento',
            },
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(fields=('tenant', 'fecha', 'tipo'), name='unique_caja_per_tenant_date_type'),
        ),
        migrations.AddConstraint(
            model_name='vehiclecategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_category_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='parkingticket',
            constraint=models.UniqueConstraint(condition=models.Q(('exit_time__isnull', True)), fields=('tenant', 'placa'), name='unique_active_plate_per_tenant'),
        ),
    ]
