# Generated by Django 5.1.3 on 2026-01-02 22:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Parqueadero'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Parqueadero'),
        ),
        migrations.AlterField(
            model_name='parkingticket',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Parqueadero'),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Parqueadero'),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3, verbose_name='Código')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('symbol', models.CharField(max_length=5, verbose_name='Símbolo')),
                ('is_default', models.BooleanField(default=False, verbose_name='Moneda principal')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Tasa de cambio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Parqueadero')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('payment_type', models.CharField(choices=[('cash', 'Efectivo'), ('credit', 'Crédito'), ('debit', 'Débito'), ('transfer', 'Transferencia'), ('digital', 'Billetera Digital'), ('qr', 'Código QR'), ('other', 'Otro')], default='cash', max_length=20, verbose_name='Tipo')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('allow_for_exit', models.BooleanField(default=True, help_text='Si se puede usar para cobrar salidas de vehículos', verbose_name='Permitir en salidas')),
                ('allow_for_contracts', models.BooleanField(default=True, help_text='Si se puede usar para pagos de mensualidades', verbose_name='Permitir en contratos')),
                ('is_credit', models.BooleanField(default=False, help_text='Si es pago a crédito (solo para clientes registrados)', verbose_name='Es crédito')),
                ('icon', models.CharField(default='fa-money-bill', max_length=50, verbose_name='Icono')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Parqueadero')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='unique_payment_method_per_tenant')],
            },
        ),
    ]
