# Generated by Django 5.1.3 on 2026-01-02 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_caja_tenant_alter_cashmovement_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingticket',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='parking.paymentmethod', verbose_name='Método de pago'),
        ),
    ]
