# Generated by Django 5.1.3 on 2026-01-03 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_add_payment_method_to_ticket'),
        ('tenants', '0002_subscriptionplan_tenant_subscription_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora de apertura')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de cierre')),
                ('initial_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Dinero inicial')),
                ('final_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dinero final')),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dinero esperado')),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diferencia')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Turno activo')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_cerrados', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Parqueadero')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-start_time'],
            },
        ),
    ]
