# Generated by Django 5.1.3 on 2026-01-03 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_add_turno_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='parking.caja', verbose_name='Caja del día'),
        ),
    ]
