# Generated by Django 5.1.3 on 2026-01-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_add_caja_to_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecategory',
            name='additional_hour_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Tarifa hora adicional'),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='first_hour_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Tarifa primera hora'),
        ),
    ]
