# Generated by Django 5.1.3 on 2026-01-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_add_expense_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecategory',
            name='extended_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Ej: 12 para tarifa de 12 horas, 24 para tarifa de día completo', null=True, verbose_name='Horas del bloque'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='extended_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa fija por el bloque de horas. Después se cobra hora adicional.', max_digits=10, null=True, verbose_name='Tarifa del bloque'),
        ),
    ]
