# Generated by Django 5.1.3 on 2026-03-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_add_extended_rate_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecategory',
            name='minimum_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo mínimo a cobrar (opcional). Ej: 15 minutos mínimo', null=True, verbose_name='Minutos mínimos'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='minute_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tarifa que se cobra por cada minuto', max_digits=8, verbose_name='Tarifa por minuto'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='rate_by_minute',
            field=models.BooleanField(default=False, help_text='Si está activo, se cobrará por minuto en lugar de por hora', verbose_name='Cobrar por minuto'),
        ),
    ]
