# Generated by Django 5.1.3 on 2026-08-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_add_placa_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingticket',
            name='apartment',
            field=models.CharField(blank=True, max_length=20, verbose_name='Apartamento'),
        ),
        migrations.AddField(
            model_name='parkingticket',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono de contacto'),
        ),
    ]
