# Generated by Django 5.1.3 on 2026-01-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Forzar cambio de contraseña en el próximo login', verbose_name='Debe cambiar contraseña'),
        ),
    ]
