# Generated by Django 5.1.3 on 2026-01-02 21:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Parqueadero')),
                ('slug', models.SlugField(help_text='Identificador interno del parqueadero', max_length=100, unique=True, verbose_name='Código único')),
                ('business_name', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('nit', models.CharField(max_length=20, verbose_name='NIT')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/', verbose_name='Logo')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('suspended', 'Suspendido'), ('trial', 'Prueba'), ('cancelled', 'Cancelado')], default='trial', max_length=20, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin del período de prueba')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Configuración personalizada del parqueadero', verbose_name='Configuración')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas internas')),
            ],
            options={
                'verbose_name': 'Parqueadero',
                'verbose_name_plural': 'Parqueaderos',
                'ordering': ['name'],
            },
        ),
    ]
