# Generated by Django 5.1.3 on 2026-01-03 00:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensual'), ('annual', 'Anual')], default='monthly', max_length=20, verbose_name='Ciclo de facturación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de suscripción'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_start',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de suscripción'),
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('confirmed_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('period_start', models.DateField(verbose_name='Inicio del período')),
                ('period_end', models.DateField(verbose_name='Fin del período')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='tenants.tenant', verbose_name='Parqueadero')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.subscriptionplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Pago de Suscripción',
                'verbose_name_plural': 'Pagos de Suscripción',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.subscriptionplan', verbose_name='Plan de suscripción'),
        ),
    ]
