# Generated by Django 5.1.3 on 2026-08-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_subscriptionplan_tenant_subscription_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_residential',
            field=models.BooleanField(default=False, help_text='Active esta opción si el parqueadero pertenece a un conjunto residencial', verbose_name='Es conjunto residencial'),
        ),
    ]
