# Generated by Django 5.1.3 on 2026-01-02 21:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Identificador único del módulo (ej: parking, reports)', max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Clase de icono (ej: fas fa-car)', max_length=50, verbose_name='Icono')),
                ('url_name', models.CharField(blank=True, help_text='Nombre de la URL de Django para este módulo', max_length=100, verbose_name='URL Name')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el menú', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='permissions.module', verbose_name='Módulo padre')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_default', models.BooleanField(default=False, help_text='Se asigna automáticamente a nuevos usuarios', verbose_name='Rol por defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Parqueadero')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True, verbose_name='Ver')),
                ('can_create', models.BooleanField(default=False, verbose_name='Crear')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Editar')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Eliminar')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='permissions.module')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='permissions.role')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Rol',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='modules',
            field=models.ManyToManyField(related_name='roles', through='permissions.RoleModulePermission', to='permissions.module', verbose_name='Módulos'),
        ),
        migrations.CreateModel(
            name='UserModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True, verbose_name='Ver')),
                ('can_create', models.BooleanField(default=False, verbose_name='Crear')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Editar')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Eliminar')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions_custom', to='permissions.module')),
            ],
            options={
                'verbose_name': 'Permiso de Usuario',
                'verbose_name_plural': 'Permisos de Usuario',
            },
        ),
    ]
