# Generated by Django 5.1.3 on 2026-01-02 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodulepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rolemodulepermission',
            unique_together={('role', 'module')},
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_role_name_per_tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='usermodulepermission',
            unique_together={('user', 'module')},
        ),
    ]
