# Generated by Django 5.1.3 on 2026-01-02 21:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('monthly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa mensual')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('expired', 'Vencido'), ('cancelled', 'Cancelado'), ('pending', 'Pendiente de pago')], default='pending', max_length=20, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Contrato Mensual',
                'verbose_name_plural': 'Contratos Mensuales',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('other', 'Otro')], default='cash', max_length=20, verbose_name='Método de pago')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('months_paid', models.PositiveIntegerField(default=1, verbose_name='Meses pagados')),
                ('is_confirmed', models.BooleanField(default=True, verbose_name='Confirmado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_payments', to='tenants.tenant', verbose_name='Parqueadero')),
            ],
            options={
                'verbose_name': 'Pago de Contrato',
                'verbose_name_plural': 'Pagos de Contratos',
                'ordering': ['-payment_date'],
            },
        ),
    ]
