# Generated by Django 5.1.3 on 2026-01-02 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monthly_contracts', '0001_initial'),
        ('parking', '0001_initial'),
        ('tenants', '0001_initial'),
        ('third_parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycontract',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_contracts', to='parking.vehiclecategory', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='monthlycontract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='monthlycontract',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Parqueadero'),
        ),
        migrations.AddField(
            model_name='monthlycontract',
            name='third_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='third_parties.thirdparty', verbose_name='Tercero'),
        ),
        migrations.AddField(
            model_name='monthlycontract',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='third_parties.thirdpartyvehicle', verbose_name='Vehículo'),
        ),
        migrations.AddField(
            model_name='contractpayment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='monthly_contracts.monthlycontract', verbose_name='Contrato'),
        ),
    ]
