# Generated by Django 5.1.3 on 2026-01-02 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_contracts', '0003_update_payment_model'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractpayment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_contract_payments', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por'),
        ),
        migrations.AlterField(
            model_name='monthlycontract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Parqueadero'),
        ),
    ]
