# Generated by Django 5.1.3 on 2026-01-02 23:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_contracts', '0004_alter_contractpayment_received_by_and_more'),
        ('parking', '0002_alter_caja_tenant_alter_cashmovement_tenant_and_more'),
        ('tenants', '0001_initial'),
        ('third_parties', '0002_alter_thirdparty_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycontract',
            name='auto_renew',
            field=models.BooleanField(default=False, verbose_name='Renovación automática'),
        ),
        migrations.AddField(
            model_name='monthlycontract',
            name='contract_type',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('biweekly', 'Quincenal'), ('weekly', 'Semanal'), ('daily', 'Diario')], default='monthly', max_length=20, verbose_name='Tipo de contrato'),
        ),
        migrations.CreateModel(
            name='SpecialRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la tarifa')),
                ('rate_type', models.CharField(choices=[('discount', 'Descuento porcentual'), ('flat', 'Tarifa plana'), ('courtesy', 'Cortesía'), ('daily_max', 'Máximo diario')], default='discount', max_length=20, verbose_name='Tipo de tarifa')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de descuento')),
                ('flat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarifa plana')),
                ('daily_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Máximo diario')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_rates', to='parking.vehiclecategory', verbose_name='Categoría')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Parqueadero')),
                ('third_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_rates', to='third_parties.thirdparty', verbose_name='Tercero')),
            ],
            options={
                'verbose_name': 'Tarifa Especial',
                'verbose_name_plural': 'Tarifas Especiales',
                'ordering': ['-created_at'],
            },
        ),
    ]
