# Generated by Django 5.1.3 on 2026-01-03 19:01

from django.conf import settings
from django.db import migrations, models


def set_payment_month_year(apps, schema_editor):
    """Set payment_month and payment_year based on payment_date for existing records.
    Handle duplicates by assigning sequential months."""
    ContractPayment = apps.get_model('monthly_contracts', 'ContractPayment')
    
    # Group payments by contract
    contract_payments = {}
    for payment in ContractPayment.objects.all().order_by('payment_date'):
        contract_id = str(payment.contract_id)
        if contract_id not in contract_payments:
            contract_payments[contract_id] = []
        contract_payments[contract_id].append(payment)
    
    # Assign sequential months to each contract's payments
    for contract_id, payments in contract_payments.items():
        for i, payment in enumerate(payments):
            if payment.payment_date:
                base_month = payment.payment_date.month
                base_year = payment.payment_date.year
                # Add offset for duplicates
                month = base_month + i
                year = base_year
                while month > 12:
                    month -= 12
                    year += 1
                payment.payment_month = month
                payment.payment_year = year
                payment.save(update_fields=['payment_month', 'payment_year'])


def reverse_migration(apps, schema_editor):
    """Reverse migration - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_contracts', '0005_add_auto_renew_and_special_rates'),
        ('parking', '0003_add_payment_method_to_ticket'),
        ('tenants', '0002_subscriptionplan_tenant_subscription_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractpayment',
            options={'ordering': ['-payment_year', '-payment_month', '-payment_date'], 'verbose_name': 'Pago de Contrato', 'verbose_name_plural': 'Pagos de Contratos'},
        ),
        migrations.RemoveField(
            model_name='contractpayment',
            name='months_paid',
        ),
        migrations.AddField(
            model_name='contractpayment',
            name='payment_month',
            field=models.PositiveIntegerField(default=1, help_text='Mes que cubre este pago (1-12)', verbose_name='Mes'),
        ),
        migrations.AddField(
            model_name='contractpayment',
            name='payment_year',
            field=models.PositiveIntegerField(default=2026, help_text='Año que cubre este pago', verbose_name='Año'),
        ),
        # Run data migration to set correct month/year values
        migrations.RunPython(set_payment_month_year, reverse_migration),
    ]
