# Generated by Django 5.1.3 on 2026-01-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_contracts', '0006_alter_contractpayment_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contractpayment',
            constraint=models.UniqueConstraint(fields=('contract', 'payment_month', 'payment_year'), name='unique_payment_per_month'),
        ),
    ]
