# Generated by Django 5.1.3 on 2026-01-03 19:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_contracts', '0007_add_unique_constraint'),
        ('parking', '0003_add_payment_method_to_ticket'),
        ('third_parties', '0002_alter_thirdparty_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlycontract',
            name='category',
        ),
        migrations.RemoveField(
            model_name='monthlycontract',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='monthlycontract',
            name='monthly_rate',
        ),
        migrations.RemoveField(
            model_name='monthlycontract',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='monthlycontract',
            name='combo_name',
            field=models.CharField(blank=True, help_text="Ej: 'Combo Familiar', 'Plan Empresarial'", max_length=100, verbose_name='Nombre del combo'),
        ),
        migrations.AddField(
            model_name='monthlycontract',
            name='combo_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa única mensual para todos los vehículos del contrato', max_digits=10, null=True, verbose_name='Tarifa combo'),
        ),
        migrations.AddField(
            model_name='monthlycontract',
            name='use_combo_rate',
            field=models.BooleanField(default=False, help_text='Si está activo, se usa una tarifa única en lugar de sumar las tarifas individuales', verbose_name='Usar tarifa combo'),
        ),
        migrations.AlterField(
            model_name='monthlycontract',
            name='third_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='third_parties.thirdparty', verbose_name='Cliente'),
        ),
        migrations.CreateModel(
            name='ContractVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa mensual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_vehicles', to='parking.vehiclecategory', verbose_name='Categoría')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='monthly_contracts.monthlycontract', verbose_name='Contrato')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_vehicles', to='third_parties.thirdpartyvehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Vehículo del Contrato',
                'verbose_name_plural': 'Vehículos del Contrato',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SpecialRate',
        ),
        migrations.AddConstraint(
            model_name='contractvehicle',
            constraint=models.UniqueConstraint(fields=('contract', 'vehicle'), name='unique_vehicle_per_contract'),
        ),
    ]
