# Generated by Django 5.1.3 on 2026-06-08 05:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_subscriptionplan_tenant_subscription_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título corto del anuncio', max_length=200, verbose_name='Título')),
                ('message', models.TextField(help_text='Mensaje completo que verán los usuarios', verbose_name='Mensaje')),
                ('announcement_type', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('critical', 'Crítico'), ('maintenance', 'Mantenimiento')], default='info', max_length=20, verbose_name='Tipo')),
                ('starts_at', models.DateTimeField(help_text='Fecha y hora desde la cual se muestra el anuncio', verbose_name='Inicio')),
                ('ends_at', models.DateTimeField(help_text='Fecha y hora hasta la cual se muestra el anuncio', verbose_name='Fin')),
                ('is_global', models.BooleanField(default=True, help_text='Si está activo, se muestra a todos los parqueaderos', verbose_name='Global')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_dismissible', models.BooleanField(default=True, help_text='Si los usuarios pueden cerrar/ocultar el banner', verbose_name='Se puede cerrar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('target_tenants', models.ManyToManyField(blank=True, help_text='Solo aplica si no es global. Seleccione los parqueaderos que verán el anuncio.', related_name='announcements', to='tenants.tenant', verbose_name='Parqueaderos específicos')),
            ],
            options={
                'verbose_name': 'Anuncio del Sistema',
                'verbose_name_plural': 'Anuncios del Sistema',
                'ordering': ['-created_at'],
            },
        ),
    ]
