# Generated by Django 5.1.3 on 2026-01-02 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('third_parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdparty',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant', verbose_name='Parqueadero'),
        ),
    ]
